### ISSUE TITLE
use with Next JS page router

### ISSUE THREAD

**Issue by charlower** [dgmjs/dgmjs#315]
Hey @niklauslee I'm trying to get dgmjs working with my Next JS project. Tried everything and finally worked out that while it works fine with Next JS app router, when using in Next JS page router I get this error: 

TypeError: Cannot read properties of null (reading 'useState')

Any idea why this might be happening? Thanks!

**Comment by niklauslee** [comment]
Since DGM.s doesn't work with SSR, please try [dynamic import](https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading#nextdynamic).

**Comment by Amtron** [comment]
add `'use client'; ` to the top of your page. This will force the page to load client side rather than server side.

**Comment by Amtron** [comment]
I'm also having this same issue.

**Comment by Amtron** [comment]
My issue was caused by a react version mismatch. I'm using react 19 and dgmjs is using react 18. To fix the issue I've added:
`
  "resolutions": {
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  }
`
to my package.json.
