### ISSUE TITLE
Refactor exports structure

### ISSUE THREAD

**Issue by niklauslee** [dgmjs/dgmjs#99]
### refactored

- `Document` --> `Doc`
- `store.doc` --> `store.root` `store.setRoot()` (Use `editor.getDoc()`)
- `handlers` namespace
- `macro` namespace
- `colors` to `themeColors`
- `canvasUtils` namespace `{ renderOnCanvas }`
- `textUtils` namespace
   - `convertTextNodeToString`
   - `preprocessTextNode`
   - `measureText`
   - `visitTextNodes`
- `exportUtils` namespace
   -  `ExportImageFormat`
   -  `ExportImageOptions`
   -  `getImageDataUrl`
   -  `getImageBlob`
   -  `getSVGImageData`
   -  `exportImageAsFile`
   -  `copyToClipboard`

**Comment by oytuntez** [comment]
Do you think `exportUtils` would work on NodeJS environments?

**Comment by niklauslee** [comment]
@oytuntez No, it requires puppeteer to be work on NodeJS.
